import type { TripPlan } from '../types';

export const mockTripPlan: TripPlan = {
  destination: '台北',
  startDate: '2026-06-01',
  endDate: '2026-06-03',
  totalBudgetMin: 8950,
  totalBudgetMax: 15700,
  dailyPlans: [
    {
      dayNumber: 1,
      date: '2026-06-01',
      weather: {
        date: '2026-06-01', weatherCode: 0, maxTemp: 32, minTemp: 25,
        precipProbability: 10, description: '晴天', emoji: '☀️',
      },
      dayBudgetMin: 2850,
      dayBudgetMax: 5100,
      lodgingArea: '西門町',
      items: [
        { id: 'd1-1', type: 'meal', mealType: 'breakfast', name: '阜杭豆漿', address: '台北市中正區忠孝東路一段108號2F', lat: 25.0445, lon: 121.5285, durationMinutes: 40, description: '排隊名店，必吃厚燒餅油條與鹹豆漿', costMin: 80, costMax: 150 },
        { id: 'd1-2', type: 'transit', transitMode: '捷運', name: '善導寺站 → 中正紀念堂站', address: '', durationMinutes: 10, description: '搭捷運藍線，一站即達', costMin: 20, costMax: 20 },
        { id: 'd1-3', type: 'attraction', category: 'outdoor', name: '中正紀念堂', address: '台北市中正區中山南路21號', lat: 25.0349, lon: 121.5219, durationMinutes: 60, description: '晴天適合戶外參觀，整點有衛兵交接儀式', costMin: 0, costMax: 0 },
        { id: 'd1-4', type: 'transit', transitMode: '步行', name: '步行至永康街', address: '', durationMinutes: 15, description: '沿金山南路步行，沿途有林蔭', costMin: 0, costMax: 0 },
        { id: 'd1-5', type: 'meal', mealType: 'lunch', name: '鼎泰豐（永康店）', address: '台北市大安區信義路二段194號', lat: 25.0337, lon: 121.5296, durationMinutes: 60, description: '世界知名小籠包，永康街本店氛圍最佳', costMin: 350, costMax: 600 },
        { id: 'd1-6', type: 'attraction', category: 'outdoor', name: '象山步道', address: '台北市信義區信義路五段150巷', lat: 25.0275, lon: 121.5720, durationMinutes: 90, description: '晴天視野極佳，可俯瞰101與台北盆地全景', costMin: 0, costMax: 0 },
        { id: 'd1-7', type: 'transit', transitMode: '捷運', name: '象山站 → 西門站', address: '', durationMinutes: 20, description: '搭捷運紅線轉藍線', costMin: 25, costMax: 25 },
        { id: 'd1-8', type: 'meal', mealType: 'dinner', name: '西門町美食街', address: '台北市萬華區漢中街', lat: 25.0421, lon: 121.5081, durationMinutes: 60, description: '各式台灣小吃匯聚，阿宗麵線、天天利必吃', costMin: 200, costMax: 400 },
        { id: 'd1-9', type: 'attraction', category: 'outdoor', name: '西門紅樓', address: '台北市萬華區成都路10號', lat: 25.0425, lon: 121.5067, durationMinutes: 45, description: '百年歷史建築，夜間有文創市集與露天酒吧', costMin: 0, costMax: 0 },
        { id: 'd1-10', type: 'lodging', name: '西門町旅館', address: '台北市萬華區西寧南路', lat: 25.0430, lon: 121.5075, durationMinutes: 0, description: '交通便利，鄰近捷運西門站', costMin: 2175, costMax: 3905 },
      ],
    },
    {
      dayNumber: 2,
      date: '2026-06-02',
      weather: {
        date: '2026-06-02', weatherCode: 61, maxTemp: 27, minTemp: 23,
        precipProbability: 80, description: '小雨', emoji: '🌧️',
      },
      dayBudgetMin: 3200,
      dayBudgetMax: 5600,
      lodgingArea: '中山區',
      items: [
        { id: 'd2-1', type: 'meal', mealType: 'breakfast', name: '美而美早餐店', address: '台北市中山區南京東路二段', lat: 25.0527, lon: 121.5317, durationMinutes: 30, description: '在地經典早餐店，蛋餅與奶茶是標配', costMin: 60, costMax: 100 },
        { id: 'd2-2', type: 'transit', transitMode: '捷運', name: '中山站 → 士林站', address: '', durationMinutes: 15, description: '搭捷運紅線北上', costMin: 20, costMax: 20 },
        { id: 'd2-3', type: 'attraction', category: 'indoor', name: '故宮博物院', address: '台北市士林區至善路二段221號', lat: 25.1024, lon: 121.5485, durationMinutes: 150, description: '雨天最適合室內參觀，翠玉白菜與肉形石必看', costMin: 350, costMax: 350 },
        { id: 'd2-4', type: 'transit', transitMode: '公車+捷運', name: '故宮 → 中山站', address: '', durationMinutes: 40, description: '搭公車至士林站再轉捷運', costMin: 35, costMax: 35 },
        { id: 'd2-5', type: 'meal', mealType: 'lunch', name: '點水樓（中山店）', address: '台北市中山區南京東路一段12號', lat: 25.0524, lon: 121.5233, durationMinutes: 60, description: '精緻江浙料理，雨天室內用餐舒適', costMin: 400, costMax: 700 },
        { id: 'd2-6', type: 'attraction', category: 'indoor', name: '台北當代藝術館', address: '台北市大同區長安西路39號', lat: 25.0502, lon: 121.5188, durationMinutes: 90, description: '下雨天逛當代藝術展，建築本身就是古蹟', costMin: 50, costMax: 50 },
        { id: 'd2-7', type: 'transit', transitMode: '捷運', name: '中山站 → 松江南京站', address: '', durationMinutes: 10, description: '搭捷運一站距離', costMin: 20, costMax: 20 },
        { id: 'd2-8', type: 'meal', mealType: 'dinner', name: '林東芳牛肉麵', address: '台北市中山區安東街4-3號', lat: 25.0520, lon: 121.5380, durationMinutes: 45, description: '米其林推薦牛肉麵，湯頭濃郁入味', costMin: 200, costMax: 350 },
        { id: 'd2-9', type: 'attraction', category: 'indoor', name: '誠品生活松菸店', address: '台北市信義區菸廠路88號', lat: 25.0435, lon: 121.5601, durationMinutes: 60, description: '雨天逛書店與文創商品，還有設計展覽', costMin: 0, costMax: 200 },
        { id: 'd2-10', type: 'lodging', name: '中山區飯店', address: '台北市中山區南京東路', lat: 25.0520, lon: 121.5310, durationMinutes: 0, description: '鄰近中山站，生活機能佳', costMin: 2015, costMax: 3775 },
      ],
    },
    {
      dayNumber: 3,
      date: '2026-06-03',
      weather: {
        date: '2026-06-03', weatherCode: 2, maxTemp: 30, minTemp: 24,
        precipProbability: 25, description: '局部多雲', emoji: '⛅',
      },
      dayBudgetMin: 2900,
      dayBudgetMax: 5000,
      lodgingArea: undefined,
      items: [
        { id: 'd3-1', type: 'meal', mealType: 'breakfast', name: '永和豆漿大王', address: '台北市大安區復興南路二段', lat: 25.0260, lon: 121.5435, durationMinutes: 30, description: '24小時營業的傳統豆漿店', costMin: 70, costMax: 120 },
        { id: 'd3-2', type: 'transit', transitMode: '捷運', name: '大安站 → 北投站', address: '', durationMinutes: 35, description: '搭捷運紅線直達北投', costMin: 30, costMax: 30 },
        { id: 'd3-3', type: 'attraction', category: 'outdoor', name: '北投溫泉博物館', address: '台北市北投區中山路二號', lat: 25.1368, lon: 121.5076, durationMinutes: 60, description: '多雲涼爽適合散步，日式建築充滿歷史氛圍', costMin: 0, costMax: 0 },
        { id: 'd3-4', type: 'attraction', category: 'outdoor', name: '地熱谷', address: '台北市北投區溫泉路', lat: 25.1383, lon: 121.5042, durationMinutes: 40, description: '壯觀的硫磺溫泉煙霧，多雲天更有仙境感', costMin: 0, costMax: 0 },
        { id: 'd3-5', type: 'meal', mealType: 'lunch', name: '滿來溫泉拉麵', address: '台北市北投區中山路1-8號', lat: 25.1370, lon: 121.5070, durationMinutes: 50, description: '北投名店，用溫泉水煮的拉麵別有風味', costMin: 200, costMax: 350 },
        { id: 'd3-6', type: 'transit', transitMode: '捷運', name: '北投站 → 淡水站', address: '', durationMinutes: 20, description: '搭捷運紅線至淡水', costMin: 25, costMax: 25 },
        { id: 'd3-7', type: 'attraction', category: 'outdoor', name: '淡水老街 & 漁人碼頭', address: '台北市淡水區中正路', lat: 25.1697, lon: 121.4413, durationMinutes: 90, description: '多雲不曬，適合沿河散步吃小吃看夕陽', costMin: 100, costMax: 300 },
        { id: 'd3-8', type: 'meal', mealType: 'dinner', name: '淡水阿給', address: '台北市淡水區真理街6-1號', lat: 25.1742, lon: 121.4376, durationMinutes: 40, description: '淡水必吃小吃，油豆腐包冬粉淋甜辣醬', costMin: 80, costMax: 150 },
        { id: 'd3-9', type: 'transit', transitMode: '捷運', name: '淡水站 → 台北車站', address: '', durationMinutes: 40, description: '搭捷運紅線返回市中心', costMin: 40, costMax: 40 },
      ],
    },
  ],
};
